### ISSUE TITLE
Create a result output, rather than failing a build

### ISSUE THREAD

**Issue by Jacoby6000** [agilepathway/label-checker#276]
Rather than failing a build, why not set a boolean flag as an output. This way users can use `if` keys to decide to skip/fail/succeed their next steps based on the output.

To maintain backward compat, this feature could be optionally enabled via an input.

**Comment by KrustyHack** [comment]
Ay,

This would be a game changer for us ! Actually we're using label check to see if a PR has "preview" label to then deploy (or not) an ephemeral environment for our developers.

But when there is not this label, PR checks is failing and it's not practical as it "block" our PRs from being merge (without force).

**Comment by johnboyes** [comment]
Hi, thanks for the suggestion @Jacoby6000 and @KrustyHack, and apologies for delay in responding!  I'll look at this over the weekend 👍🏻

**Comment by johnboyes** [comment]
@Jacoby6000 @KrustyHack I've started work on this, apologies for the time its taken!  What would be a good name for the new input which, if set, will not fail the build, do you think?  I'm thinking  something like `allow_failure`?

I'm also thinking to set the boolean job output always, regardless of whether the `allow_failure` input is set, as there's no harm in doing so.

Feedback welcome.

**Comment by KrustyHack** [comment]
Ay @johnboyes ,

Don't worry ! You don't have to apologies ;)

`allow_failure` looks good to me !

**Comment by johnboyes** [comment]
@Jacoby6000 @KrustyHack this is now implemented, in release [1.2.0](https://github.com/agilepathway/label-checker/releases/tag/v1.2.0).  Very grateful for any feedback, and thanks for the suggestion for this feature 🙏🏻

**Comment by johnboyes** [comment]
ps the feature is documented [here](https://github.com/agilepathway/label-checker#allow-failure-mode), in the README

**Comment by KrustyHack** [comment]
Thanks a lot for your work ! :+1:
