### ISSUE TITLE
Highlight error in output?

### ISSUE THREAD

**Issue by devnev** [agilepathway/label-checker#330]
When this github action outputs an error, it currently prints a line prefixed with `Error:`, but the line isn't highlighted in any way, making it slightly harder to spot. In other actions, I've seen errors highlighted in red in the github UI (and users accustomed to that are more likely to miss the non-highlighted error from this action).

I think this is done by issuing an error workflow command as per https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message. These docs have all sorts of parameters for file and line numbers, but I'm pretty sure they can all be skipped and the output can be `::error::{message}`

**Comment by devnev** [comment]
<img width="430" alt="Screenshot 2023-02-01 at 09 45 52" src="https://user-images.githubusercontent.com/79550/216008205-aaaefe20-dc71-4a0d-89d7-191a1901eaf3.png">

**Comment by johnboyes** [comment]
Thanks.  This may not be achievable for this label checker action, as it's a [Docker container action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action), meaning that the action doesn't use workflow commands but rather generates the error message in code (see [here](https://github.com/agilepathway/label-checker/blob/e7993d100ee8329a28c419e3c09f0aca13f71ba6/internal/github/action.go#L60)).  I'll have a look though to see if it's possible to access the workflow commands programatically - guessing it may not be possible but will have a look.

**Comment by devnev** [comment]
The javascript workflow commands are all [wrappers around output to stdout](https://github.com/actions/toolkit/blob/1589a5c066fbe34ed1c828e9b81b9f206f9a3a40/packages/core/src/command.ts#L23) (e.g. `::error::{message}` as noted above) or specific files like `$GITHUB_OUTPUT`, so it might still work - but agreed that the docs really aren't clear on whether it does or not.

**Comment by johnboyes** [comment]
This was closed in error (automatically) by #332.  Reopening.

**Comment by johnboyes** [comment]
Hi @devnev, I've implemented and released this in [`1.3.1`](https://github.com/agilepathway/label-checker/releases/tag/v1.3.1) 👍🏻
