### ISSUE TITLE
Docker latest tag is not updated with latest version and missing ARM platform

### ISSUE THREAD

**Issue by andrejex** [agilepathway/label-checker#419]
Docker latest tag is pointed to a 3 months old release. And only platform available is AMD which caused some issues trying to run this workflow on self-hosted runners.

**Comment by johnboyes** [comment]
Thanks for raising this, @andrejex, I'll have time to look into this in the next few days, will keep you posted.

**Comment by johnboyes** [comment]
Hi @andrejex, here's an update on this issue:

> Docker latest tag is pointed to a 3 months old release

I've restored the missing `latest` tag for new releases, in [v1.6.15](https://github.com/agilepathway/label-checker/releases/tag/v1.6.15).  The bug crept in in [v1.6.0](https://github.com/agilepathway/label-checker/releases/tag/v1.6.0), when migrating to a newer major version of the [Docker build push action](https://github.com/docker/build-push-action).  To avoid any future regressions I've [added a test](https://github.com/agilepathway/label-checker/blob/fa6bd1c7a30f89e09dbfee369bcce0b4f8c1901f/.github/workflows/github_tag_and_release.yml#L75-L96) which checks that any new releases are always tagged with `latest`, as well as with the new semantic version number. 

> only platform available is AMD which caused some issues trying to run this workflow on self-hosted runners

We added arm64 support in the same v1.6.0 release which introduced the latest tag bug.  I'm going to test the arm64 support to make sure it's working properly, in the meantime feel free to give it a try too and let me know if it's working for you, thanks v much for any feedback 🙏🏻
