### ISSUE TITLE
Missing Security policy

### ISSUE THREAD

**Issue by w0rmr1d3r** [agilepathway/label-checker#439]
Hello 👋 ,

Are there plans to create a Security Policy?
Currently that tab appears empty: https://github.com/agilepathway/label-checker/security

Thanks in advance

**Comment by johnboyes** [comment]
hi @w0rmr1d3r, thanks for raising this.   It's a good suggestion indeed, I'll add this tomorrow. The policy will be to have [private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability), I'll reply to this thread when it's setup.  Thanks, John

**Comment by w0rmr1d3r** [comment]
Really great! thank you for adding it in such a short time! 🔝
